# Generated by Django 6.0.1 on 2026-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('processed', False)), fields=['created_at'], name='outbox_created_idx')],
            },
        ),
    ]
