# Generated by Django 6.0.1 on 2026-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_application_company_resume_vacancy_and_more'),
        ('chat', '0003_remove_conversation_ad_conversation_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
