# Generated by Django 6.0.1 on 2026-07-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_application_company_resume_vacancy_and_more'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='ad',
        ),
        migrations.AddField(
            model_name='conversation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.application'),
        ),
    ]
